WITH raw_loanstatus AS (
    SELECT
        *
    FROM {{ source('raw_data', 'loanstatus') }}
)

SELECT
    _AIRBYTE_RAW_ID::VARCHAR(36)            AS _AIRBYTE_RAW_ID,
    _AIRBYTE_EXTRACTED_AT::TIMESTAMP_TZ     AS _AIRBYTE_EXTRACTED_AT,
    _AIRBYTE_META::VARIANT                  AS _AIRBYTE_META,
    LOAN_STATUS::VARCHAR(50)                AS LOAN_STATUS,
    LOAN_STATUS_KEY::NUMBER                 AS LOAN_STATUS_KEY,
    VERIFICATION_STATUS::VARCHAR(50)        AS VERIFICATION_STATUS,
    VERIFICATION_STATUS_JOINT::VARCHAR(50)  AS VERIFICATION_STATUS_JOINT

FROM raw_loanstatus
