WITH raw_borrower AS (
    select * from {{ source('raw_data', 'borrower') }}
)

SELECT
    _AIRBYTE_RAW_ID::VARCHAR(36) AS _AIRBYTE_RAW_ID,
    _AIRBYTE_EXTRACTED_AT::TIMESTAMP_TZ AS _AIRBYTE_EXTRACTED_AT,
    _AIRBYTE_META::VARIANT AS _AIRBYTE_META,
    ZIP_CODE::VARCHAR(10) AS ZIP_CODE,
    EMP_TITLE::VARCHAR AS EMP_TITLE,
    ADDR_STATE::VARCHAR(2) AS ADDR_STATE,
    ANNUAL_INC::NUMBER(12,2) AS ANNUAL_INC,
    EMP_LENGTH::VARCHAR AS EMP_LENGTH,
    BORROWER_KEY::NUMBER AS BORROWER_KEY,
    HOME_OWNERSHIP::VARCHAR(20) AS HOME_OWNERSHIP
FROM  raw_borrower
