with raw_factloans as (
    select * from {{ source('raw_data', 'factloans') }}
)

select
        cast(_AIRBYTE_RAW_ID as varchar) as airbyte_raw_id,
        cast(_AIRBYTE_EXTRACTED_AT as timestamp) as airbyte_extracted_at,
        cast(_AIRBYTE_META as varchar) as airbyte_meta,

        cast(ID as bigint) as loan_id,
        cast(DTI as numeric(10,2)) as dti,
        cast(URL as varchar) as url,
        cast(ISSUE_D as date) as issue_d,
        cast(replace(INT_RATE, '%', '') as numeric(5,2)) as int_rate,
        cast(DTI_JOINT as numeric(10,2)) as dti_joint,
        cast(LOAN_AMNT as numeric(18,2)) as loan_amnt,
        cast(OUT_PRNCP as numeric(18,2)) as out_principal,
        cast(PYMNT_PLAN as varchar) as payment_plan,
        cast(RECOVERIES as numeric(18,2)) as recoveries,
        cast(FUNDED_AMNT as numeric(18,2)) as funded_amount,
        cast(INSTALLMENT as numeric(18,2)) as installment,
        cast(POLICY_CODE as integer) as policy_code,
        cast(TOT_CUR_BAL as numeric(18,2)) as total_current_balance,
        cast(TOTAL_PYMNT as numeric(18,2)) as total_payment,
        cast(BORROWER_KEY as bigint) as borrower_key,
        cast(HARDSHIP_DPD as integer) as hardship_dpd,
        cast(LAST_PYMNT_D as date) as last_payment_date,
        cast(NEXT_PYMNT_D as date) as next_payment_date,
        cast(TOT_COLL_AMT as numeric(18,2)) as total_collection_amount,
        cast(TOTAL_BAL_IL as numeric(18,2)) as total_balance_il,
        cast(DEFERRAL_TERM as integer) as deferral_term,
        cast(HARDSHIPS_KEY as bigint) as hardships_key,
        cast(OUT_PRNCP_INV as numeric(18,2)) as out_principal_inv,
        cast(TOTAL_REC_INT as numeric(18,2)) as total_rec_int,
        cast(TOTAL_BC_LIMIT as numeric(18,2)) as total_bc_limit,
        cast(FUNDED_AMNT_INV as numeric(18,2)) as funded_amount_inv,
        cast(HARDSHIP_AMOUNT as numeric(18,2)) as hardship_amount,
        cast(HARDSHIP_LENGTH as integer) as hardship_length,
        cast(HARDSHIP_REASON as varchar) as hardship_reason,
        cast(LAST_PYMNT_AMNT as numeric(18,2)) as last_payment_amount,
        cast(LOAN_STATUS_KEY as integer) as loan_status_key,
        cast(REVOL_BAL_JOINT as numeric(18,2)) as revol_bal_joint,
        cast(TOT_HI_CRED_LIM as numeric(18,2)) as total_hi_credit_limit,
        cast(TOTAL_PYMNT_INV as numeric(18,2)) as total_payment_inv,
        cast(TOTAL_REC_PRNCP as numeric(18,2)) as total_rec_principal,
        cast(ANNUAL_INC_JOINT as numeric(18,2)) as annual_income_joint,
        cast(LOAN_DETAILS_KEY as bigint) as loan_details_key,
        cast(TOTAL_REV_HI_LIM as numeric(18,2)) as total_rev_hi_lim,
        cast(HARDSHIP_END_DATE as date) as hardship_end_date,
        cast(TOTAL_BAL_EX_MORT as numeric(18,2)) as total_balance_ex_mort,
        cast(CREDIT_HISTORY_KEY as bigint) as credit_history_key,
        cast(LAST_CREDIT_PULL_D as date) as last_credit_pull_date,
        cast(TOTAL_REC_LATE_FEE as numeric(18,2)) as total_rec_late_fee,
        cast(_AB_SOURCE_FILE_URL as varchar) as source_file_url,
        cast(HARDSHIP_START_DATE as date) as hardship_start_date,
        cast(LAST_FICO_RANGE_LOW as integer) as last_fico_range_low,
        cast(HARDSHIP_LOAN_STATUS as varchar) as hardship_loan_status,
        cast(LAST_FICO_RANGE_HIGH as integer) as last_fico_range_high,
        cast(COLLECTION_RECOVERY_FEE as numeric(18,2)) as collection_recovery_fee,
        cast(PAYMENT_PLAN_START_DATE as date) as payment_plan_start_date,
        cast(TOTAL_IL_HIGH_CREDIT_LIMIT as numeric(18,2)) as total_il_high_credit_limit,
        cast(HARDSHIP_LAST_PAYMENT_AMOUNT as numeric(18,2)) as hardship_last_payment_amount,
        cast(_AB_SOURCE_FILE_LAST_MODIFIED as timestamp) as source_file_last_modified,
        cast(HARDSHIP_PAYOFF_BALANCE_AMOUNT as numeric(18,2)) as hardship_payoff_balance_amount,
        cast(ORIG_PROJECTED_ADDITIONAL_ACCRUED_INTEREST as numeric(18,2)) as orig_projected_additional_accrued_interest

from raw_factloans
